config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'profile#index'
  resources :users
  resources :password_resets

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length: { minimum: 8 }, on: :user_create_action
  validates :username, presence: true, length: { minimum: 5 }, on: :update
  before_create { generate_token(:auth_token) }
  after_create :send_welcome_email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  def new; end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def create
    user = User.find_by_email(params[:email])
    user&.send_password_reset
    redirect_to root_url, notice: 'Email sent with password reset instructions.'
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 6.hours.ago
      redirect_to new_password_reset_path, alert: 'Password reset has expired.'
    elsif @user.update_attributes(user_params)
      redirect_to root_url, notice: 'Password has been reset.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/profile_controller.rb
# frozen_string_literal: true

class ProfileController < ApplicationController
  before_action :authorize

  def index; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token
      end
      redirect_to root_url, notice: 'Logged in!'
    else
      redirect_to '/login', alert: 'Invalid email or password'
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to '/login', notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :find_user, only: %i[edit update show destroy]

  def new
    @user = User.new
  end

  def edit; end

  def show; end

  def create
    @user = User.new(user_params)
    @user.username = @user.email.split('@').first
    if @user.save
      cookies.permanent[:auth_token] = @user.auth_token
      redirect_to '/', notice: 'Sign up successfully.'
    else
      redirect_to '/signup', alert: @user.errors.full_messages.join(', ')
    end
  end

  def update
    if @user.update(user_params)
      redirect_to '/', notice: 'User updated successfully.'
    else
      redirect_to edit_user_path(@user), alert: @user.errors.full_messages.join(', ')
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      redirect_to '/login', notice: 'Successfully deleted user account.'
    else
      flash[:alert] = 'Error while deleting user account.'
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/password_resets_helper.rb
# frozen_string_literal: true

module PasswordResetsHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistrationSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Signed in as <b><%= current_user.username %></b> | <%= link_to 'Profile', edit_user_path(current_user) %> | <%= link_to "Logout", '/logout' %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %><br><br>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div><br>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div><br>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: (@user.id ? user_path(@user) : users_path) do |f| %>
  <% if @user.id %>
    Username: <br><%= f.text_field :username %><br>
  <% end %>
  <% if @user.id %>
  	Email: <br><%= f.text_field :email, disabled: true %><br>
  <% else %>
  	Email: <br><%= f.text_field :email %><br>
  <% end %>
  Password: <br><%= f.password_field :password %><br>
  Password Confirmation: <br><%= f.password_field :password_confirmation %><br><br>
  <%= f.submit @user.id ? "Update" : "Submit" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>
<h2>Cancel my account</h2>
<%= link_to 'Cancel my account', @user, method: :delete, data: { confirm: "You sure?" } %>

app/views/users/new.html.erb
<h1>Signup!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'profile/index' %>